Repository SBNSoftware/sbndcode, pull requests merged in 2021-04, with the labels that each got.

#97 TPC readout window reduction
  .gitignore
  sbndcode/AnalysisTree/AnalysisTree_module.cc
  sbndcode/AnalysisTree/CMakeLists.txt
  sbndcode/AnalysisTree/analysistreemodule.fcl
  sbndcode/JobConfigurations/base/evd_sbnd_3drift.fcl
  sbndcode/JobConfigurations/base/prod_eminus_0.1_0.9_sbnd.fcl
  sbndcode/JobConfigurations/base/prodcosmics_corsika_sbnd.fcl
  sbndcode/JobConfigurations/base/prodcosmics_cry_sbnd.fcl
  sbndcode/JobConfigurations/base/prodgenie_common_cosmic_sbnd.fcl
  sbndcode/JobConfigurations/base/prodmarley_sbnd_1event.fcl
  sbndcode/JobConfigurations/base/prodsingle_common_sbnd.fcl
  sbndcode/JobConfigurations/base/prodsingle_sbnd.fcl
  sbndcode/JobConfigurations/standard/detsim/detsim_sce.fcl
  sbndcode/JobConfigurations/standard/g4/g4_sce.fcl
  sbndcode/JobConfigurations/standard/g4/g4_sce_simphotontime_filter.fcl
  sbndcode/JobConfigurations/standard/gen/overlay/other_flux_config/other/prodoverlay_corsika_cosmics_proton_genie_nu_spill_gsimple-newflux-v1_cryostat.fcl
  sbndcode/JobConfigurations/standard/gen/overlay/prodoverlay_corsika_cosmics_proton_genie_intrnue_spill_tpc_sbnd_3drift_windows.fcl
  sbndcode/JobConfigurations/standard/gen/overlay/prodoverlay_corsika_cosmics_proton_genie_nu_spill_tpc_sbnd_3drift_windows.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_dualmu_5GeV_fixposcontained_openingangle1.0degree.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_electron_100-2250MeV_fixposcontained_fixangle.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_electron_pi+_bnblike.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_electron_pi+_bnblike_anode_forwards_inwards.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_electron_pi+_bnblike_cathode_forwards_inwards.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_electron_pi+_bnblike_forward.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_gamma_100-2250MeV_fixposcontained_fixangle.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_gamma_pi+_bnblike.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_gamma_pi+_bnblike_forward.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_mu_100-1257MeV_fixposcontained_fixangle.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_mu_10GeV_cathodecrossing.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_mu_10GeV_frontcorners_cornertocorner.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_mu_proton_bnblike_anode_forwards_inwards.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_mu_proton_bnblike_cathode_forwards_inwards.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_muplus_stopping_fromtop.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_pi+_100-2250MeV_fixposcontained_fixangle.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_pi0_100-2250MeV_fixposcontained_fixangle.fcl
  sbndcode/JobConfigurations/standard/gen/single/prodsingle_proton_200-2250MeV_fixposcontained_fixangle.fcl
  sbndcode/JobConfigurations/standard/reco/reco1_sce.fcl
  sbndcode/LArSoftConfigurations/1drift_services_sbnd.fcl
  sbndcode/LArSoftConfigurations/3drift_services_sbnd.fcl
  sbndcode/LArSoftConfigurations/corsika_sbnd.fcl
  sbndcode/LArSoftConfigurations/cosmic_common_sbnd.fcl
  sbndcode/LArSoftConfigurations/cry_sbnd.fcl
  sbndcode/LArSoftConfigurations/drop_raw_products.fcl
  sbndcode/LArSoftConfigurations/evdservices_sbnd.fcl
  sbndcode/LArSoftConfigurations/singles_sbnd.fcl
  sbndcode/Utilities/detectorclocks_sbnd.fcl
  sbndcode/Utilities/detectorproperties_sbnd.fcl
Labels: enhancement

#101 update CI cfg file
  test/ci/ci_tests.cfg
Labels: maintenance, test

#102 Add 1-drift services file for backwards compatibility
  sbndcode/LArSoftConfigurations/1drift_services_sbnd_legacy.fcl
Labels: backwards compatibility

#100 Updates and fixes to optical trigger alg
  sbndcode/OpDetSim/opDetSBNDTriggerAlg.cc
  sbndcode/OpDetSim/opDetSBNDTriggerAlg.hh
  sbndcode/OpDetSim/optriggeralg_sbnd.fcl
Labels: enhancement
