Repository SBNSoftware/sbndcode, pull requests merged in 2024-01, with the labels that each got.

#392 updated hitdumper XA ophit label
  sbndcode/Commissioning/HitDumper_module.cc
  sbndcode/Commissioning/fcls/hitdumpermodule.fcl
  sbndcode/Commissioning/fcls/run_hitdumper.fcl
Labels: bug

#395 Feature/rodrigoa det sim x as update
  sbndcode/OpDetReco/OpDeconvolution/job/opdeconvolution_sbnd.fcl
  sbndcode/OpDetReco/OpDeconvolution/job/sbnd_flashfinder_deco.fcl
  sbndcode/OpDetReco/OpDeconvolution/job/sbnd_ophitfinder_deco.fcl
  sbndcode/OpDetReco/OpHit/job/ophitconfig_sbnd.fcl
  sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc
  sbndcode/OpDetSim/DigiArapucaSBNDAlg.hh
  sbndcode/OpDetSim/digi_arapuca_sbnd.fcl
  sbndcode/OpDetSim/opDetDigitizerWorker.cc
  sbndcode/OpDetSim/sbnd_pds_mapping.json
Labels: enhancement

#404 Patch for SimpleFlash
  sbndcode/FlashMatch/flashmatch_sbnd.fcl
Labels: maintenance

#403 Razzled
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_sce.fcl
Labels: enhancement
