Repository SBNSoftware/sbndcode, pull requests merged in 2024-10, with the labels that each got.

#527 Hotfix to CRT offline
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_v7.txt
  sbndcode/ChannelMaps/CRT/crt_channel_map_service.fcl
  sbndcode/Geometry/GeometryWrappers/CRTGeoAlg.cc
  sbndcode/Geometry/GeometryWrappers/CRTGeoAlg.h
Labels: bug, crt

#523 Update T0 default to be in configuration fcl
  sbndcode/JobConfigurations/base/prodsingle_sbnd.fcl
  sbndcode/LArSoftConfigurations/gen/singles_sbnd.fcl
Labels: enhancement

#525 Update ophitfinder parameters to run on raw waveforms
  sbndcode/OpDetReco/OpHit/job/ophit_finder_sbnd.fcl
  sbndcode/Trigger/PMT/pmtArtdaqFragmentProducer.fcl
  sbndcode/Trigger/PMT/pmtsoftwaretriggerproducer.fcl
Labels: reco1/reco2

#526 CRT Offline
  sbndcode/CRT/CRTAna/CMakeLists.txt
  sbndcode/CRT/CRTAna/CRTAnalysis_module.cc
  sbndcode/CRT/CRTAna/CRTCalibAna_module.cc
  sbndcode/CRT/CRTAna/run_crtana.fcl
  sbndcode/CRT/CRTAna/run_crtana_data.fcl
  sbndcode/CRT/CRTBackTracker/CRTBackTrackerAlg.cc
  sbndcode/CRT/CRTBackTracker/CRTBackTrackerAlg.h
  sbndcode/CRT/CRTBackTracker/crtbacktrackeralg_sbnd.fcl
  sbndcode/CRT/CRTEventDisplay/CRTEventDisplayAlg.cc
  sbndcode/CRT/CRTEventDisplay/CRTEventDisplayAlg.h
  sbndcode/CRT/CRTEventDisplay/CRTEventDisplay_module.cc
  sbndcode/CRT/CRTEventDisplay/crteventdisplay_sbnd.fcl
  sbndcode/CRT/CRTEventDisplay/crteventdisplayalg_sbnd.fcl
  sbndcode/CRT/CRTEventDisplay/run_crteventdisplay.fcl
  sbndcode/CRT/CRTEventDisplay/run_crteventdisplay_data.fcl
  sbndcode/CRT/CRTReco/CMakeLists.txt
  sbndcode/CRT/CRTReco/CRTClusterCharacterisationAlg.cc
  sbndcode/CRT/CRTReco/CRTClusterCharacterisationAlg.h
  sbndcode/CRT/CRTReco/CRTClusterProducer_module.cc
  sbndcode/CRT/CRTReco/CRTStripHitProducer_module.cc
  sbndcode/CRT/CRTReco/CRTTrackProducer_module.cc
  sbndcode/CRT/CRTReco/crtrecoproducers_sbnd.fcl
  sbndcode/CRT/CRTReco/run_crtreco_data.fcl
  sbndcode/CRT/CRTSimulation/CRTDetSimAlg.cxx
  sbndcode/CRT/CRTSimulation/CRTDetSimAlg.h
  sbndcode/CRT/CRTSimulation/CRTDetSimParams.h
  sbndcode/CRT/CRTSimulation/crtsimmodules_sbnd.fcl
  sbndcode/CRT/CRTTPCMatching/CRTSpacePointMatchAlg.cc
  sbndcode/CRT/CRTTPCMatching/CRTSpacePointMatchAlg.h
  sbndcode/CRT/CRTTPCMatching/CRTTrackMatchAlg.cc
  sbndcode/CRT/CRTTPCMatching/CRTTrackMatchAlg.h
  sbndcode/CRT/CRTTPCMatching/crttpcmatchingproducers_sbnd.fcl
  sbndcode/Calibration/CRT/CMakeLists.txt
  sbndcode/Calibration/CRT/CalibService/CMakeLists.txt
  sbndcode/Calibration/CRT/CalibService/CRTCalibService.h
  sbndcode/Calibration/CRT/CalibService/CRTCalibService_service.cc
  sbndcode/Calibration/CRT/CalibService/SBNDCRTPedestals_v1.txt
  sbndcode/Calibration/CRT/CalibService/SBNDCRTTimingOffsets_v1.txt
  sbndcode/Calibration/CRT/CalibService/crt_calib_service.fcl
  sbndcode/Calibration/CRT/crtskim_sbnd.fcl
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_v7.txt
  sbndcode/ChannelMaps/CRT/crt_channel_map_service.fcl
  sbndcode/Commissioning/HitDumper_module.cc
  sbndcode/Commissioning/fcls/hitdumpermodule.fcl
  sbndcode/Geometry/GeometryWrappers/CMakeLists.txt
  sbndcode/Geometry/GeometryWrappers/CRTGeoAlg.cc
  sbndcode/Geometry/GeometryWrappers/CRTGeoAlg.h
  sbndcode/Geometry/GeometryWrappers/crtgeoalg_sbnd.fcl
  sbndcode/JobConfigurations/standard/reco/reco1_data.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
  sbndcode/ToFStudies/ToFAnalyzer_module.cc
  sbndcode/ToFStudies/ToFProducer_module.cc
  sbndcode/Trigger/ArtdaqFragmentProducer_module.cc
  sbndcode/Trigger/CRT/CRTArtdaqFragmentProducer.fcl
  sbndcode/Trigger/CRT/CRTArtdaqFragmentProducer_module.cc
  sbndcode/Trigger/artdaqfragmentproducer.fcl
Labels: crt, reco1/reco2

#530 Update CI cpu and memory limits
  test/ci/ci_tests.cfg
Labels: maintenance

#516 Accommodate changes to recob::Hit
  sbndcode/TPC1DSignalProcessing/tools/TrackHitEfficiencyAnalysis_tool.cc
  sbndcode/gallery/galleryAnalysis/HitAnalysisAlg.cpp
Labels: maintenance

#522 TPC-only CAF fcl for SBND data
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_data.fcl
Labels: tpc, caf

#528 Refactor reco2 workflow, and promote standard_reco2_sbnd.fcl back to the main workflow again
  sbndcode/Commissioning/fcls/reco2_comm.fcl
  sbndcode/JobConfigurations/README.md
  sbndcode/JobConfigurations/standard/reco/config/drops_reco2.fcl
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_sce.fcl
  sbndcode/JobConfigurations/standard/standard_reco2_sbnd.fcl
  test/JobConfigurations/fast_simulation_reconstruction_test_electrons.sh
  test/JobConfigurations/fast_simulation_reconstruction_test_muons.sh
  test/ci/fcl_file_checks.list
  test/ci/sbnd_ci_nucosmics_reco2_quick_test_sbndcode.fcl
  test/ci/sbnd_ci_single_reco2_quick_test_sbndcode.fcl
Labels: maintenance

#531 Cluster3D Save Space Points
  sbndcode/JobConfigurations/standard/reco/config/drops_reco1.fcl
  sbndcode/LArSoftConfigurations/cluster_sbnd.fcl
Labels: maintenance, reco1/reco2

#533 Bug fix for running hitdumper without crt strip hits present
  sbndcode/Commissioning/HitDumper_module.cc
Labels: crt

#535 update timesize (the size of the frame in samples minus one) to 1143
  sbndcode/Decoders/TPC/SBNDTPCDecoderDefaults.fcl
Labels: tpc

#542 fcl to run all the decoders
  sbndcode/Decoders/CMakeLists.txt
  sbndcode/Decoders/run_decoders_job.fcl
Labels: enhancement
