Repository SBNSoftware/sbndcode, pull requests merged in 2024-02, with the labels that each got.

#414 Update unit tests to use WireCell workflow
  sbndcode/JobConfigurations/standard/g4/g4_dirt_filter.fcl
  sbndcode/JobConfigurations/standard/standard_g4_sbnd.fcl
  sbndcode/WireCell/wirecell_pgrapher_detsim_sbnd.fcl
  sbndcode/WireCell/wirecell_sim_rawdigits_sp.fcl
  sbndcode/WireCell/wirecell_sim_sp_sbnd.fcl
  sbndcode/WireCell/wirecell_tbb_deposet_detsim_sbnd.fcl
  test/JobConfigurations/fast_simulation_reconstruction_test_electrons.sh
  test/JobConfigurations/fast_simulation_reconstruction_test_muons.sh
Labels: maintenance

#413 Quick fix to the hitfinder module to work with the Raw XARAPUCA waveforms
  sbndcode/OpDetReco/OpHit/job/ophit_finder_sbnd.fcl
Labels: bug

#415 Move bnb_common config fcl to sbncode
  sbndcode/JobConfigurations/standard/gen/MeVPrtl/bnb_kaon_common.fcl
  sbndcode/JobConfigurations/standard/gen/MeVPrtl/hnl_config.fcl
Labels: enhancement
