Repository SBNSoftware/sbndcode, pull requests merged in 2025-02, with the labels that each got.

#566 Update reco1 to use channel status service
  sbndcode/LArSoftConfigurations/mlreco_sbnd.fcl
  sbndcode/LArSoftConfigurations/services_sbnd.fcl
Labels: bug, reco1/reco2

#563 Integrate CVN model
  CMakeLists.txt
  sbndcode/CMakeLists.txt
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
  sbndcode/SBNDCVN/CMakeLists.txt
  sbndcode/SBNDCVN/fcls/CMakeLists.txt
  sbndcode/SBNDCVN/fcls/SBNDCVNMapper.fcl
  sbndcode/SBNDCVN/fcls/run_SBNDCVNEvaTest.fcl
  sbndcode/SBNDCVN/fcls/run_SBNDCVNEvaluator.fcl
  sbndcode/SBNDCVN/fcls/run_SBNDCVNMapper.fcl
  sbndcode/SBNDCVN/fcls/run_SBNDCVNTest.fcl
  sbndcode/SBNDCVN/fcls/run_SBNDWireCheck.fcl
  sbndcode/SBNDCVN/fcls/run_SBNDZlibMaker.fcl
  sbndcode/SBNDCVN/module_helpers/CMakeLists.txt
  sbndcode/SBNDCVN/module_helpers/SBNDICVNMapper.cxx
  sbndcode/SBNDCVN/module_helpers/SBNDICVNMapper.h
  sbndcode/SBNDCVN/module_helpers/SBNDICVNZlibMaker.cxx
  sbndcode/SBNDCVN/module_helpers/SBNDICVNZlibMaker.h
  sbndcode/SBNDCVN/module_helpers/SBNDITFNetHandler.h
  sbndcode/SBNDCVN/module_helpers/SBNDPixelMapProducer.cxx
  sbndcode/SBNDCVN/module_helpers/SBNDPixelMapProducer.h
  sbndcode/SBNDCVN/module_helpers/classes.h
  sbndcode/SBNDCVN/module_helpers/classes_def.xml
  sbndcode/SBNDCVN/modules/CMakeLists.txt
  sbndcode/SBNDCVN/modules/SBNDCVNEvaluator_module.cc
  sbndcode/SBNDCVN/modules/SBNDCVNMapper_module.cc
  sbndcode/SBNDCVN/modules/SBNDCVNTest_module.cc
  sbndcode/SBNDCVN/modules/SBNDCVNZlibMaker_module.cc
  sbndcode/SBNDCVN/modules/SBNDTFNetHandler_tool.cc
  sbndcode/SBNDCVN/tf/CMakeLists.txt
  sbndcode/SBNDCVN/tf/tf_graph.cc
  sbndcode/SBNDCVN/tf/tf_graph.h
Labels: tpc

#609 CRT Data Timing (Cherry-Picked)
  sbndcode/CRT/CRTAna/CRTAnalysis_module.cc
  sbndcode/CRT/CRTReco/CMakeLists.txt
  sbndcode/CRT/CRTReco/CRTStripHitProducer_module.cc
  sbndcode/CRT/CRTReco/crtrecoproducers_sbnd.fcl
Labels: crt, reco1/reco2, data

#627 Exclude CVN in the code and fcl files for now
  sbndcode/CMakeLists.txt
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
Labels: reco1/reco2

#592 FilterChoppy_module.cc
  sbndcode/Calibration/DQM/FilterChoppy_module.cc
Labels: bug

#596 Updated list of unresponsive channels
  sbndcode/Utilities/badchannels_sbnd.fcl
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/chndb-base.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/chndb-perfect.jsonnet
Labels: detsim, data

#606 WireCell NF+SP updates (teardrop mitigation)
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/chndb-base.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/chndb-perfect.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/nf.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/params.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/sp-filters.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/wcls-sim-drift-depoflux-nf-sp.jsonnet
Labels: tpc, data

#615 X-ARAPUCAs Offline Decoder v2.0: timing update & bugfix
  sbndcode/Decoders/XARAPUCA/SBNDXARAPUCADecoder_module.cc
  sbndcode/Decoders/XARAPUCA/run_xarapucadecoder.fcl
  sbndcode/Decoders/XARAPUCA/xarapucadecoder.fcl
Labels: bug, pds

#616 Add X-ARAPUCAs offline decoder to the production chain
  sbndcode/Decoders/run_decoders_job.fcl
Labels: pds, data

#621 Increase space in hitdumper for CRT
  sbndcode/Commissioning/fcls/hitdumpermodule.fcl
Labels: crt

#628 PMT (Beam) Metrics Analyzer: Allow stream labels
  sbndcode/Trigger/MetricAnalyzer_module.cc
  sbndcode/Trigger/MetricFilter_module.cc
  sbndcode/Trigger/metricfilter.fcl
Labels: data

#632 Update CRT Pedestals
  sbndcode/Calibration/CRT/CalibService/SBNDCRTPedestals_v2.txt
  sbndcode/Calibration/CRT/CalibService/crt_calib_service.fcl
Labels: maintenance, crt

#634 CRT North Wall Reco Bugfix
  sbndcode/Geometry/GeometryWrappers/CRTGeoAlg.h
Labels: geometry, reco1/reco2, data

#635 CRT data fcl updates
  sbndcode/CRT/CRTReco/crtrecoproducers_sbnd.fcl
  sbndcode/CRT/CRTReco/run_crtreco_data.fcl
Labels: crt, reco1/reco2, data

#622 fix simchannel label to make calohit tmatch work
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
Labels: caf

#633 Feature/acastill new pmt calibration
  sbndcode/OpDetReco/OpDeconvolution/Alg/opdeconvolution_alg_data.fcl
  sbndcode/OpDetReco/OpDeconvolution/job/opdeconvolution_sbnd_data.fcl
  sbndcode/OpDetReco/OpDeconvolution/job/sbnd_ophitfinder_deco_data.fcl
  sbndcode/OpDetReco/OpHit/SBNDOpHitFinder_module.cc
Labels: reco1/reco2

#636 Reenable CVN
  sbndcode/CMakeLists.txt
  sbndcode/SBNDCVN/module_helpers/SBNDICVNMapper.cxx
  sbndcode/SBNDCVN/module_helpers/SBNDPixelMapProducer.cxx
  sbndcode/SBNDCVN/modules/CMakeLists.txt
  sbndcode/SBNDCVN/modules/SBNDCVNEvaluator_module.cc
Labels: tpc

#611 PMT Decoder Update: reading PTB HLTs correctly
  sbndcode/Decoders/PMT/SBNDPMTDecoder_module.cc
  sbndcode/Decoders/PMT/pmtdecoder.fcl
Labels: pds, data

#614 Add branches for time-walk and propagation delay correction in CRTAnalysis_module.cc
  sbndcode/CRT/CRTAna/CRTAnalysis_module.cc
  sbndcode/CRT/CRTAna/run_crtana.fcl
Labels: enhancement, crt

#618 Feature/rohanr crtdqm v2
  sbndcode/Commissioning/CMakeLists.txt
  sbndcode/Commissioning/HitDumper_module.cc
  sbndcode/Commissioning/fcls/hitdumpermodule.fcl
Labels: crt, data

#619 Create run_mpvmpr_sbnd_intime.fcl
  sbndcode/JobConfigurations/standard/gen/MultiPart/run_mpvmpr_sbnd_intime.fcl
Labels: simulation

#639 Adds a CAFMaker FCL for cosmics
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_sce_cosmics.fcl
Labels: bug

#642 Save pedestal and RMS calculation in ChannelInfo object per TPC channel.
  sbndcode/Decoders/TPC/SBNDTPCDecoder.h
  sbndcode/Decoders/TPC/SBNDTPCDecoder_module.cc
Labels: enhancement

#648 Add cvn back to fcl files
  sbndcode/CMakeLists.txt
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
Labels: reco1/reco2

#650 Add full osc file
  sbndcode/JobConfigurations/standard/gen/overlay/prodoverlay_corsika_cosmics_proton_genie_rockbox_fullosc_sce.fcl
Labels: enhancement

#645 Updating Clock to the New Porch Size
  sbndcode/Utilities/detectorclocks_sbnd.fcl
  sbndcode/WireCell/cfg/pgrapher/common/params.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/params.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/wcls-sim-drift-depoflux-nf-sp.jsonnet
  sbndcode/WireCell/wcsimsp_sbnd.fcl
Labels: bug
