Repository SBNSoftware/sbndcode, pull requests merged in 2025-06, with the labels that each got.

#744 Add Data-motivated pandoraShower modules that make use of the data calo alg
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
  sbndcode/SBNDPandora/pandoramodules_sbnd.fcl
Labels: reco1/reco2

#740 WireCell Coherent Noise Updated Grouping
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/chndb-base.jsonnet
Labels: tpc

#601 Create README.md
  README.md
Labels: documentation
