Repository SBNSoftware/sbndcode, pull requests merged in 2025-04, with the labels that each got.

#652 Revert "Revert "Save pedestal and RMS calculation in ChannelInfo object per TPC channel.""
  sbndcode/Decoders/TPC/SBNDTPCDecoder.h
  sbndcode/Decoders/TPC/SBNDTPCDecoder_module.cc
Labels: enhancement

#667 Inherit genie config from genie_beam_settings.fcl in sbncode
  sbndcode/LArSoftConfigurations/gen/genie_sbnd.fcl
Labels: enhancement, simulation

#685 Typo fix in flashmatch_sbnd.fcl
  sbndcode/FlashMatch/flashmatch_sbnd.fcl
Labels: bug, caf

#686 Fix indexing for LLTs in PTBAna
  sbndcode/PTBAna/PTBAnalysis_module.cc
Labels: bug, trigger

#693 save traj points for cosmics
  sbndcode/LArG4/larg4_services_sbnd.fcl
Labels: simulation

#702 Drop PDS and CRT DAQ fragments, and Wiener wires
  sbndcode/Decoders/run_decoders_job.fcl
  sbndcode/JobConfigurations/base/decoder_drops.fcl
  sbndcode/JobConfigurations/base/reco_drops.fcl
Labels: reco1/reco2, data

#704 Change number of events in data caf CI test from 2 to 5
  test/ci/ci_tests.cfg
Labels: bug, test

#694 CRT-TPC Matching with Data
  sbndcode/CRT/CRTAna/CRTAnalysis_module.cc
  sbndcode/CRT/CRTAna/crtana_sbnd.fcl
  sbndcode/CRT/CRTAna/run_crtana.fcl
  sbndcode/CRT/CRTAna/run_crtana_data_tpc_matching.fcl
  sbndcode/CRT/CRTEventDisplay/CRTEventDisplayAlg.cc
  sbndcode/CRT/CRTEventDisplay/CRTEventDisplayAlg.h
  sbndcode/CRT/CRTEventDisplay/crteventdisplayalg_sbnd.fcl
  sbndcode/CRT/CRTTPCMatching/CMakeLists.txt
  sbndcode/CRT/CRTTPCMatching/CRTSpacePointMatchAlg.cc
  sbndcode/CRT/CRTTPCMatching/CRTSpacePointMatchAlg.h
  sbndcode/CRT/CRTTPCMatching/CRTSpacePointMatching_module.cc
  sbndcode/CRT/CRTTPCMatching/CRTTrackMatchAlg.cc
  sbndcode/CRT/CRTTPCMatching/CRTTrackMatchAlg.h
  sbndcode/CRT/CRTTPCMatching/CRTTrackMatching_module.cc
  sbndcode/CRT/CRTTPCMatching/crttpcmatchingproducers_sbnd.fcl
  sbndcode/CRT/CRTUtils/CRTCommonUtils.cc
  sbndcode/CRT/CRTUtils/CRTCommonUtils.h
  sbndcode/Decoders/run_decoders_job_no_choppy.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
Labels: crt, tpc, reco1/reco2, data

#696 GDML v02 04
  sbndcode/Geometry/GeometryWrappers/CRTGeoAlg.h
  sbndcode/Geometry/GeometryWrappers/CRTOrientationMaps.h
  sbndcode/Geometry/gdml/sbnd_v02_04.gdml
  sbndcode/Geometry/gdml/sbnd_v02_04_base.gdml
  sbndcode/Geometry/gdml/sbnd_v02_04_nowires.gdml
  sbndcode/Geometry/geometry_sbnd.fcl
  sbndcode/LArSoftConfigurations/gen/genie_sbnd.fcl
  test/Geometry/geometry_unit_test_sbnd.h
  test/Geometry/test_geometry_sbnd.fcl
Labels: crt, geometry

#710 Fixed x offset
  sbndcode/BlipRecoSBND/Alg/BlipRecoAlg.cc
  sbndcode/BlipRecoSBND/Utils/BlipUtils.cc
  sbndcode/BlipRecoSBND/blipreco_configs.fcl
Labels: reco1/reco2

#637 Provide intial space charge effect calibration
  sbndcode/LArSoftConfigurations/enable_spacecharge_services_sbnd.fcl
  sbndcode/LArSoftConfigurations/enable_spacecharge_services_sbnd_2D_DriftSimOnly.fcl
  sbndcode/LArSoftConfigurations/spacecharge_sbnd.fcl
  sbndcode/SpaceCharge/SpaceChargeSBND.cxx
  sbndcode/SpaceCharge/SpaceChargeSBND.h
Labels: tpc

#682 Move crt space points to reco1 so Supera can consume them
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco1.fcl
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
  sbndcode/JobConfigurations/standard/reco/reco1_data.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
Labels: crt

#689 Python interfaces to LArSoft [5/5]
  sbndcode/gallery/galleryAnalysis/CMakeLists.txt
  sbndcode/gallery/python/CMakeLists.txt
  sbndcode/gallery/python/LArSoftUtils.py
  sbndcode/gallery/python/README.md
  sbndcode/gallery/python/ROOTutils.py
  sbndcode/gallery/python/SBNDservices.py
  sbndcode/gallery/python/SBNDutils.py
  sbndcode/gallery/python/cppUtils.py
  sbndcode/gallery/python/galleryUtils.py
Labels: enhancement

#690 Fix signedness of cluster timing sets
  sbndcode/CRT/CRTAna/CRTAnalysis_module.cc
Labels: bug, crt

#701 Feature/acastill pmt eff
  sbndcode/LArSoftConfigurations/opticalproperties_sbnd.fcl
  sbndcode/OpDetReco/OpHit/job/ophit_finder_sbnd.fcl
  sbndcode/OpDetSim/DigiPMTSBNDAlg.cc
  sbndcode/OpDetSim/DigiPMTSBNDAlg.hh
  sbndcode/OpDetSim/digi_pmt_sbnd.fcl
Labels: detsim

#703 Feature/caf pot
  sbndcode/JobConfigurations/base/cafmakerjob_sbnd_data_base.fcl
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_data_bnblight.fcl
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_data_bnbzerobias.fcl
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_data_offbeamlight.fcl
  test/ci/sbnd_ci_data_offBeamZeroBias_caf_quick_test_sbndcode.fcl
Labels: caf

#706 Update OpT0Finder PMT Efficiencies
  sbndcode/OpT0Finder/job/opt0finder_sbnd.fcl
  sbndcode/OpT0Finder/job/opt0finder_sbnd_data.fcl
  sbndcode/Trigger/run_metricfilter.fcl
Labels: pds, reco1/reco2, data

#713 Adding nonSCE cosmic MC cafmaker fcl
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_cosmics.fcl
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_sce.fcl
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
Labels: enhancement

#717 [Bug] Store all MCParticles
  sbndcode/LArG4/larg4_services_sbnd.fcl
Labels: bug, simulation

#673 Feature/acastill pmtdatabaseinterface
  sbndcode/Calibration/CMakeLists.txt
  sbndcode/Calibration/PDSDatabaseInterface/CMakeLists.txt
  sbndcode/Calibration/PDSDatabaseInterface/IPMTCalibrationDatabaseService.h
  sbndcode/Calibration/PDSDatabaseInterface/PMTCalibrationDatabase.h
  sbndcode/Calibration/PDSDatabaseInterface/PMTCalibrationDatabaseProvider.cxx
  sbndcode/Calibration/PDSDatabaseInterface/PMTCalibrationDatabaseProvider.h
  sbndcode/Calibration/PDSDatabaseInterface/PMTCalibrationDatabaseService_service.cc
  sbndcode/Calibration/PDSDatabaseInterface/pmtcalibrationdatabase_sbnd.fcl
  sbndcode/LArSoftConfigurations/services_sbnd.fcl
  ups/product_deps
Labels: enhancement

#719 Updating calibration constants with values measured using 2025A Spring Dev Samples
  sbndcode/LArSoftConfigurations/calorimetry_sbnd.fcl
Labels: reco1/reco2, caf

#721 Add tpcpdbarycentermatching to standard workflow
  sbndcode/JobConfigurations/base/cafmakerjob_sbnd_data_base.fcl
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
Labels: pds

#726 Simulate dirt neutrinos in MPV
  sbndcode/JobConfigurations/standard/gen/MultiPart/multipartvertex_sbnd.fcl
Labels: simulation

#725 Adding T0 correction to raw digit processing for calib purpose
  sbndcode/JobConfigurations/standard/reco/reco2_data_rawdigit_sbnd.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_mc_rawdigit_sbnd.fcl
Labels: calibration

#734 bump version
  ups/product_deps
Labels: maintenance

#681 Feature/acastill flash drift distance
  sbndcode/JobConfigurations/standard/reco/reco1_data.fcl
  sbndcode/OpDetReco/OpDeconvolution/job/run_decohitfinder_data.fcl
  sbndcode/OpDetReco/OpDeconvolution/job/sbnd_flashfinder_deco_data.fcl
  sbndcode/OpDetReco/OpFlash/FlashTools/DriftEstimatorPMTRatio_tool.cc
  sbndcode/OpDetReco/OpFlash/job/sbnd_driftestimatoralgo.fcl
  sbndcode/OpDetReco/OpFlash/job/sbnd_flashfinder_data.fcl
Labels: reco1/reco2

#705 CRT Calibrated Timing Corrections
  sbndcode/CRT/CRTAna/CRTAnalysis_module.cc
  sbndcode/CRT/CRTReco/CRTClusterCharacterisationAlg.cc
  sbndcode/CRT/CRTReco/CRTClusterProducer_module.cc
  sbndcode/CRT/CRTReco/CRTStripHitProducer_module.cc
  sbndcode/Calibration/CRT/CalibService/CRTCalibService.h
  sbndcode/Calibration/CRT/CalibService/CRTCalibService_service.cc
  sbndcode/Calibration/CRT/CalibService/SBNDCRTT0CableOffsets_v1.txt
  sbndcode/Calibration/CRT/CalibService/SBNDCRTT0CalibOffsets_v1.txt
  sbndcode/Calibration/CRT/CalibService/SBNDCRTT1CableOffsets_v1.txt
  sbndcode/Calibration/CRT/CalibService/SBNDCRTT1CalibOffsets_v1.txt
  sbndcode/Calibration/CRT/CalibService/crt_calib_service.fcl
  sbndcode/Commissioning/HitDumper_module.cc
  sbndcode/Geometry/GeometryWrappers/CRTGeoAlg.cc
  sbndcode/Geometry/GeometryWrappers/CRTGeoAlg.h
Labels: crt, data

#707 Feature/aantonak crtveto
  sbndcode/CRT/CMakeLists.txt
  sbndcode/CRT/CRTVeto/CMakeLists.txt
  sbndcode/CRT/CRTVeto/CRTVetoProducer_module.cc
  sbndcode/CRT/CRTVeto/crtvetoproducer_sbnd.fcl
  sbndcode/CRT/CRTVeto/run_crtveto.fcl
  sbndcode/CRT/CRTVeto/run_crtveto_data.fcl
  sbndcode/CRT/CRTVeto/run_crtveto_data_tophat.fcl
  sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
Labels: crt

#730 Save OpFlash information in CAF files in SBND
  sbndcode/JobConfigurations/base/cafmakerjob_sbnd_data_base.fcl
  sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
Labels: enhancement

#733 Update parameters of in-time cosmic MC gen filter modules
  sbndcode/Filters/fcls/filtersgenintime_sbnd.fcl
  sbndcode/Filters/fcls/filterssimphotonlitetime_sbnd.fcl
  sbndcode/Filters/fcls/filterssimphotontime_sbnd.fcl
Labels: simulation

#731 Update reco2_data.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
Labels: bug, crt, reco1/reco2
