Repository SBNSoftware/sbndcode, pull requests merged in 2025-09, with the labels that each got.

#794 Change RockBox Min Energy Deposited
  sbndcode/Filters/SimEnergyDepFakeTriggerFilter_module.cc
  sbndcode/Filters/fcls/simenergydepfaketriggerfilter.fcl
  sbndcode/JobConfigurations/standard/gen/genie_corsika/prodgenie_corsika_proton_rockbox100_sbnd.fcl
  sbndcode/JobConfigurations/standard/gen/genie_corsika/prodgenie_corsika_proton_rockbox_lowenergydirt_sbnd.fcl
Labels: simulation

#803 Frame Shift Module to Correct Timing in Data - PR For Spring Production
  sbndcode/JobConfigurations/base/cafmakerjob_sbnd_data_base.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
  sbndcode/Timing/CMakeLists.txt
  sbndcode/Timing/FrameShift/CMakeLists.txt
  sbndcode/Timing/FrameShift/FrameShift_module.cc
  sbndcode/Timing/FrameShift/frameshift_sbnd_data.fcl
  sbndcode/Timing/FrameShift/run_frameshift.fcl
  sbndcode/Timing/SBNDRawTimingObj.h
Labels: breaking change, reco1/reco2

#809 Update calibration database to provide new attributes
  sbndcode/Calibration/PDSDatabaseInterface/PMTCalibrationDatabase.h
  sbndcode/Calibration/PDSDatabaseInterface/PMTCalibrationDatabaseProvider.cxx
  sbndcode/Calibration/PDSDatabaseInterface/PMTCalibrationDatabaseProvider.h
  sbndcode/Calibration/PDSDatabaseInterface/pmtcalibrationdatabase_sbnd.fcl
Labels: enhancement

#807 Feature/acastill tpcpmt bfm upgrade
  sbndcode/TPCPMTBarycenterMatching/CMakeLists.txt
  sbndcode/TPCPMTBarycenterMatching/TPCPMTBarycenterMatching_module.cc
  sbndcode/TPCPMTBarycenterMatching/job/sbnd_tpcpmt3dbarycentermatching_config.fcl
Labels: reco1/reco2

#804 Frame Shift Module to Correct Timing in Data - PR For Develop
  sbndcode/JobConfigurations/base/cafmakerjob_sbnd_data_base.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
  sbndcode/Timing/CMakeLists.txt
  sbndcode/Timing/FrameShift/CMakeLists.txt
  sbndcode/Timing/FrameShift/FrameShift_module.cc
  sbndcode/Timing/FrameShift/frameshift_sbnd_data.fcl
  sbndcode/Timing/FrameShift/run_frameshift.fcl
Labels: breaking change, reco1/reco2

#783 Changing detsim drops for detvars
  sbndcode/JobConfigurations/base/detsim_drops.fcl
Labels: maintenance, detsim

#828 hot fix fcl to run reco1 w/ dnn roi
  sbndcode/JobConfigurations/dnnroi/reco1_data_dnnroi.fcl
Labels: bug

#829 Patching for production - filtered + dropped workflow
  sbndcode/JobConfigurations/dnnroi/reco1_data_dnnroi.fcl
Labels: bug

#831 Setting CAF cnnid wire to look for DNN ROI
  sbndcode/JobConfigurations/dnnroi/cafmakerjob_sbnd_data_sce_bnblight_dnnroi.fcl
  sbndcode/JobConfigurations/dnnroi/cafmakerjob_sbnd_data_sce_offbeamlight_dnnroi.fcl
  sbndcode/JobConfigurations/dnnroi/cafmakerjob_sbnd_sce_cosmics_dnnroi.fcl
  sbndcode/JobConfigurations/dnnroi/cafmakerjob_sbnd_sce_systtools_and_fluxwgt_dnnroi.fcl
Labels: bug
