Repository SBNSoftware/sbndcode, pull requests merged in 2025-01, with the labels that each got.

#597 [Bug fix] Remove detector clock service from PTB Ana
  sbndcode/PTBAna/run_ptbana.fcl
Labels: bug

#539 WireCell Noise-Filtering Updates (Data + Simulation)
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/chndb-base.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/chndb-perfect.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/funcs.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/nf.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/params.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/simparams.jsonnet
  sbndcode/WireCell/cfg/pgrapher/experiment/sbnd/wcls-nf-data.jsonnet
  sbndcode/WireCell/wcsp_data_sbnd.fcl
Labels: tpc, detsim, data

#541 PMT Decoder Updates: Timing Data Product + Timing CAEN addition + more
  sbndcode/CMakeLists.txt
  sbndcode/Decoders/PMT/CMakeLists.txt
  sbndcode/Decoders/PMT/SBNDPMTDecoder_module.cc
  sbndcode/Decoders/PMT/pmtdecoder.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data.fcl
  sbndcode/Timing/CMakeLists.txt
  sbndcode/Timing/SBNDRawTimingObj.h
  sbndcode/Timing/classes.h
  sbndcode/Timing/classes_def.xml
Labels: pds, data

#552 First version of the X-ARAPUCAs decoder (V1740B digitizers)
  sbndcode/Decoders/CMakeLists.txt
  sbndcode/Decoders/XARAPUCA/CMakeLists.txt
  sbndcode/Decoders/XARAPUCA/SBNDXARAPUCADecoder_module.cc
  sbndcode/Decoders/XARAPUCA/run_xarapucadecoder.fcl
  sbndcode/Decoders/XARAPUCA/xarapucadecoder.fcl
Labels: pds

#556 Data TPC Signal Processing: use calibrated electronics response by default
  sbndcode/WireCell/wcsp_data_sbnd.fcl
Labels: tpc, data

#558 Adding reco fcls that keep RawDigit data products
  sbndcode/JobConfigurations/standard/reco/config/drops_reco1.fcl
  sbndcode/JobConfigurations/standard/reco/reco1_data_rawdigit.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data_rawdigit.fcl
Labels: tpc, reco1/reco2, data

#559 Add workflow for PMT data reconstruction
  sbndcode/JobConfigurations/standard/reco/reco1_data.fcl
  sbndcode/OpDetAnalyzer/PDSAnalyzer/job/run_sbndpds_ana_data.fcl
  sbndcode/OpDetAnalyzer/PDSAnalyzer/job/run_sbndpds_ana_data_withWaveforms.fcl
  sbndcode/OpDetReco/OpDeconvolution/Alg/CMakeLists.txt
  sbndcode/OpDetReco/OpDeconvolution/Alg/OpDeconvolutionAlgWienerData_tool.cc
  sbndcode/OpDetReco/OpDeconvolution/Alg/opdeconvolution_alg_data.fcl
  sbndcode/OpDetReco/OpDeconvolution/job/opdeconvolution_sbnd_data.fcl
  sbndcode/OpDetReco/OpDeconvolution/job/run_decohitfinder_data.fcl
  sbndcode/OpDetReco/OpDeconvolution/job/sbnd_ophitfinder_deco_data.fcl
Labels: pds, reco1/reco2, data

#562 Update to sbnd_data v01_26_00
  ups/product_deps
Labels: enhancement, maintenance, pds

#564 Save space for reco1 data stage by dropping cluster3d
  sbndcode/JobConfigurations/base/reco_drops.fcl
Labels: maintenance, reco1/reco2, data

#565 Add Analyzer and Filter for PMT Flash Metrics from PMT Software Trigger
  sbndcode/Trigger/CMakeLists.txt
  sbndcode/Trigger/MetricAnalyzer_module.cc
  sbndcode/Trigger/MetricFilter_module.cc
  sbndcode/Trigger/metricfilter.fcl
  sbndcode/Trigger/run_metricana.fcl
  sbndcode/Trigger/run_metricfilter.fcl
Labels: data

#598 Rebase of hlay_gdml_v02_03
  sbndcode/CRT/CRTReco/CRTClusterCharacterisationAlg.h
  sbndcode/CRT/CRTReco/CRTStripHitProducer_module.cc
  sbndcode/Calibration/CRT/CalibService/SBNDCRTPedestals_v1.txt
  sbndcode/Calibration/CRT/CalibService/SBNDCRTTimingOffsets_v1.txt
  sbndcode/ChannelMaps/CRT/README.md
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_Commissioning_v1.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_Commissioning_v2.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_Commissioning_v3.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_Commissioning_v4.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_Commissioning_v5.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_v1.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_v2.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_v3.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_v4.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_v5.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_v6.txt
  sbndcode/ChannelMaps/CRT/SBNDCRTChannelMap_v7.txt
  sbndcode/ChannelMaps/CRT/crt_channel_map_service.fcl
  sbndcode/Geometry/GeometryWrappers/CRTGeoAlg.h
  sbndcode/Geometry/gdml/sbnd_v02_03.gdml
  sbndcode/Geometry/gdml/sbnd_v02_03_base.gdml
  sbndcode/Geometry/gdml/sbnd_v02_03_nowires.gdml
  sbndcode/Geometry/geometry_sbnd.fcl
Labels: crt, geometry

#600 Update hitdumper defaults to store CRT info
  sbndcode/Commissioning/fcls/hitdumpermodule.fcl
Labels: crt

#602 de-caplitalize Services and change the total tick count to 3427 for d…
  sbndcode/JobConfigurations/base/evd_sbnd_data.fcl
Labels: maintenance

#603 waveform workflow support
  sbndcode/JobConfigurations/standard/reco/config/drops_reco1.fcl
  sbndcode/JobConfigurations/standard/reco/reco1_data_rawdigit_storefilteredevents.fcl
  sbndcode/JobConfigurations/standard/reco/reco2_data_rawdigit.fcl
Labels: reco1/reco2

#610 Removing Gallery From CI
  test/ci/ci_tests.cfg
Labels: bug
